services:
  microservice1:
    container_name: microservice1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql_ms1:5432/db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - SERVER_PORT=8090
    networks:
      - network
      - microservice1
    volumes:
      - ms1-logs:/opt/app/log
  postgresql:
    container_name: postgresql_ms1
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - microservice1
  filebeat:
    container_name: filebeat_ms1
    image: docker.elastic.co/beats/filebeat:8.15.2
    entrypoint: filebeat -e -strict.perms=false
    user: root
    volumes:
      - ./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
      - ms1-logs:/var/app/log
    networks:
      - network

volumes:
  ms1-logs:


networks:
  microservice1:
    external: false
  network:
    external: true