services:
  nginx:
    image: 'nginx:latest'
    volumes:
      - ./mcroservices_nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - network

networks:
  network:
    external: true