services:
    rabbitmq:
      container_name: rabbitmq
      image: 'rabbitmq:3-management'
      environment:
        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
        - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      ports:
        - '5672:5672'
      networks:
        - network


networks:
  network:
    external: true