services:
  microservice2:
    container_name: microservice2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql_ms2:5432/db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SERVER_PORT=8091
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
    networks:
      - network
      - microservice2
    volumes:
      - ms2-logs:/opt/app/log
  postgresql:
    container_name: postgresql_ms2
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    networks:
      - microservice2
  filebeat:
    container_name: filebeat_ms2
    image: docker.elastic.co/beats/filebeat:8.15.2
    entrypoint: filebeat -e -strict.perms=false
    user: root
    volumes:
      - ./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
      - ms2-logs:/var/app/log
    networks:
      - network

volumes:
  ms2-logs:



networks:
  microservice2:
    external: false
  network:
    external: true